# Generated by Django 2.2 on 2019-04-25 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voltages', '0002_auto_20190424_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
