# Generated by Django 2.2 on 2019-04-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voltages', '0003_auto_20190425_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_coil_1', models.DecimalField(decimal_places=3, max_digits=65)),
                ('voltage_coil_2', models.DecimalField(decimal_places=3, max_digits=65)),
                ('voltage_generated_by_user', models.DecimalField(decimal_places=3, max_digits=65)),
                ('activity', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
