# Generated by Django 2.2 on 2019-04-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltages', '0004_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='user',
        ),
    ]
